#!/bin/bash
#echo rails-nginx-unicorn
#pushd rails-nginx-unicorn > /dev/null
#make || exit 1
#popd > /dev/null

#echo testapp
#pushd testapp > /dev/null
#make || exit 1
#popd > /dev/null

echo db
pushd db > /dev/null
make || exit 1
popd > /dev/null

