#!/bin/bash
pushd squid-deb-proxy > /dev/null
make || exit 1
make run || exit 1
popd > /dev/null

pushd ubuntu > /dev/null
make || exit 1
popd > /dev/null

exit 0

pushd ruby
make
if [ $? -ne 0 ]; then
  exit 1
fi
popd

exit 0

pushd geminabox
make
if [ $? -ne 0 ]; then
  exit 1
fi
popd

exit 0

pushd rails-nginx-unicorn
make
if [ $? -ne 0 ]; then
  exit 1
fi
popd

pushd testapp
make
if [ $? -ne 0 ]; then
  exit 1
fi
popd

