#!/bin/bash
pushd ubuntu
make
if [ $? -ne 0 ]; then
  exit 1
fi
popd

pushd squid-deb-proxy
make
if [ $? -ne 0 ]; then
  exit 1
fi
popd

pushd geminabox
make
if [ $? -ne 0 ]; then
  exit 1
fi
popd

exit 0

pushd ruby
make
if [ $? -ne 0 ]; then
  exit 1
fi
popd

pushd rails-nginx-unicorn
make
if [ $? -ne 0 ]; then
  exit 1
fi
popd

pushd testapp
make
if [ $? -ne 0 ]; then
  exit 1
fi
popd

